### ISSUE TITLE
Successor for project owner

### ISSUE THREAD

**Issue by fr43nk** [OpenNingia/vscode-clearcase#94]
Hi,

I want to open the discussion about the new maintainer of this project.
@OpenNingia said, he has not enough time to keep on working on it. So I think a successor is needed.
At work I still use CC, so it is also in my interest to keep this extension up to date.

**Comment by OpenNingia** [comment]
As I said I don't use ClearCase at work anymore, not in a daily basis at least. This extension has gathered quite a pool of users  so it needs a motivated maintainer badly.

Now we need to agree on how to do that technically.

The vscode team already approached this issue and there are some options:

https://github.com/microsoft/vscode/issues/21478

The code is the easiest part (we can fork it or I can give you maintainer access to it).
The trouble is the extension in the marketplace. 

I can give you permission to publish in my stead or you could fork it.

Personally I am against forking the extension because we would confuse users and I'm sure we would lose a bunch of them in the transition.

What do you think?

**Comment by fr43nk** [comment]
I think, to keep everything as is, maybe it is the best way to keep your repository as the main.
So everyone who has forked it in the past will get informed if something changed in the repo.
If this is ok with you I think we should give the shared access rights rights a try. My username is Fr43nk.

**Comment by fr43nk** [comment]
@OpenNingia what is your plan for the vscode marketplace access? If you want to keep control on that process it is ok with me. However I need a way to trigger you to publish a new version of the extension. Like right now 😄

**Comment by OpenNingia** [comment]
@fr43nk I've committed a workflow to enable automatic publishing. You should be able to trigger it by creating a new Github Release. I didn't try it thou. If it doesn't work I will release the extension manually.

**Comment by fr43nk** [comment]
Ah ok, sounds great. I will test it right now.

**Comment by OpenNingia** [comment]
@fr43nk The publish job didn't run :/. 
I made a fix. Can you try to delete the release and create it again?

**Comment by fr43nk** [comment]
@OpenNingia it looks like publish job didn't run.

**Comment by OpenNingia** [comment]
@fr43nk now it ran. I deleted the tag and re-created it so it got my workflow fix.

**Comment by fr43nk** [comment]
@OpenNingia That is very nice. So hopefully the next time it will work again to bother you to much 😄
